import os
import uuid
import io
import re
import json
import pandas as pd
from typing import Dict, Any, List
from fastapi import FastAPI, UploadFile, File, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from dotenv import load_dotenv

# Import your local modules
from bias_engine import analyze_dataset_comprehensive, compute_fairness_metrics
from langchain_utils import generate_bias_narrative, analyze_hidden_correlations

# Load environment variables
load_dotenv()

app = FastAPI(title="Neural Stack API")

# Updated CORS for production/hackathon flexibility
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], # Allows your frontend to connect from anywhere (ideal for demos)
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
    expose_headers=["*"],
)

# --- IN-MEMORY STORAGE ---
DATAFRAMES: Dict[str, pd.DataFrame] = {}

# --- HELPER FUNCTIONS ---

def simulate_reweighting_improvements(metrics: Dict[str, Any]) -> Dict[str, Any]:
    improved = {
        "privileged_group": metrics["privileged_group"],
        "selection_rates": dict(metrics["selection_rates"]),
        "metrics": {},
    }
    metric_items = sorted(metrics.get("metrics", {}).items(), key=lambda x: x[0])
    for idx, (group, values) in enumerate(metric_items):
        improvement_factor = 0.20 + ((idx % 3) * 0.05)
        di = values.get("disparate_impact")
        spd = values.get("statistical_parity_difference")
        improved_di = float(di) + ((1.0 - float(di)) * improvement_factor) if di is not None else None
        improved_spd = float(spd) * (1.0 - improvement_factor) if spd is not None else None
        improved["metrics"][group] = {
            "disparate_impact": improved_di,
            "statistical_parity_difference": improved_spd,
            "improvement_factor": round(improvement_factor, 2),
        }
    return improved

def format_audit_report_markdown(title: str, narrative: str, charts: Dict[str, Any], executive_summary: str = "") -> str:
    chart_json = json.dumps(charts or {}, indent=2)
    sections = [f"# {title}", "", "## Executive Summary", executive_summary or "_Not provided_", "", 
                "## AI Narrative", narrative or "_Not provided_", "", "## Chart Data Snapshot", 
                "```json", chart_json, "```", "", "## Notes", "- Generated by Neural Stack audit pipeline."]
    return "\n".join(sections)

def extract_red_flags(summary: str) -> list[str]:
    lines = [line.strip() for line in summary.splitlines() if line.strip()]
    bullet_lines = []
    for line in lines:
        normalized = re.sub(r"^\s*[-*]\s*", "", line)
        if any(term in normalized.lower() for term in ("risk", "warning", "red flag", "bias", "disparity")):
            bullet_lines.append(normalized)
        if len(bullet_lines) >= 5: break
    return bullet_lines if bullet_lines else ["Manual verification required: specific flags not parsed."]

def build_fallback_agent_summary(dataset_stats: Dict[str, Any]) -> str:
    return f"Fallback: Scanned {dataset_stats.get('row_count')} rows. LLM reasoning unavailable. Check high-correlation features for proxy risk."

# --- API ENDPOINTS ---

@app.get("/")
async def read_root():
    return {"status": "online", "message": "Neural Stack API - Asia-South1 Deployment"}

@app.post("/upload")
async def upload_csv(file: UploadFile = File(...)):
    if not (file.filename.endswith(".csv") or file.content_type in ("text/csv", "application/vnd.ms-excel")):
        raise HTTPException(status_code=400, detail="Only CSV files are supported")
    contents = await file.read()
    try:
        df = pd.read_csv(io.BytesIO(contents))
    except Exception as exc:
        raise HTTPException(status_code=400, detail=f"Failed to parse CSV: {exc}")
    
    data_id = str(uuid.uuid4())
    DATAFRAMES[data_id] = df
    keywords = ["race", "gender", "age", "zip", "ethnicity"]
    return {
        "id": data_id,
        "columns": list(df.columns),
        "dtypes": {col: str(dtype) for col, dtype in df.dtypes.items()},
        "potential_sensitive_attributes": [col for col in df.columns if any(k in col.lower() for k in keywords)],
    }

@app.post("/analyze")
async def analyze(data: dict):
    data_id, target, sensitive = data.get("data_id"), data.get("target_column"), data.get("sensitive_column")
    if data_id not in DATAFRAMES: raise HTTPException(status_code=404, detail="Data not found")
    df = DATAFRAMES[data_id]
    try:
        metrics = compute_fairness_metrics(df, target, sensitive, data.get("privileged_value"))
        comp = analyze_dataset_comprehensive(df, sensitive, target, data.get("privileged_value"))
        return {"data_id": data_id, "analysis": metrics, "comprehensive_analysis": comp}
    except Exception as e:
        raise HTTPException(status_code=400, detail=str(e))

@app.post("/narrative")
async def generate_narrative(data: dict):
    data_id = data.get("data_id")
    if data_id not in DATAFRAMES: raise HTTPException(status_code=404, detail="Data not found")
    df = DATAFRAMES[data_id]
    try:
        metrics = compute_fairness_metrics(df, data.get("target_column"), data.get("sensitive_column"), data.get("privileged_value"))
        narrative = generate_bias_narrative(metrics, list(df.columns), data.get("sensitive_column"))
        return {"data_id": data_id, "narrative": narrative}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

class AgentReasoningResponse(BaseModel):
    summary: str
    red_flags: List[str]
    status: str

@app.post("/agent-reasoning", response_model=AgentReasoningResponse)
async def agent_reasoning(data: dict):
    data_id = data.get("data_id")
    if data_id not in DATAFRAMES: raise HTTPException(status_code=404, detail="Data not found")
    df = DATAFRAMES[data_id]
    dataset_stats = {"row_count": len(df), "column_count": len(df.columns), "columns": list(df.columns)}
    try:
        summary = analyze_hidden_correlations(dataset_stats)
        return {"summary": summary, "red_flags": extract_red_flags(summary), "status": "complete"}
    except Exception:
        return {"summary": build_fallback_agent_summary(dataset_stats), "red_flags": [], "status": "fallback"}

@app.post("/simulate-mitigation")
async def simulate_mitigation(data: dict):
    data_id = data.get("data_id")
    if data_id not in DATAFRAMES: raise HTTPException(status_code=404, detail="Data not found")
    try:
        before = compute_fairness_metrics(DATAFRAMES[data_id], data.get("target_column"), data.get("sensitive_column"), data.get("privileged_value"))
        return {"before_metrics": before, "after_metrics": simulate_reweighting_improvements(before)}
    except Exception as e:
        raise HTTPException(status_code=400, detail=str(e))

@app.post("/report")
async def generate_report(data: dict):
    markdown = format_audit_report_markdown(data.get("title", "Audit Report"), data.get("narrative"), data.get("charts"), data.get("executive_summary", ""))
    return {"report_markdown": markdown}

# --- CLOUD RUN ENTRY POINT ---
if __name__ == "__main__":
    import uvicorn
    # Use the PORT environment variable provided by Cloud Run
    port = int(os.environ.get("PORT", 8080))
    # host 0.0.0.0 is required to accept outside traffic
    uvicorn.run(app, host="0.0.0.0", port=port)
